version: "3"
services:
  postgres:
    image: "docker.io/postgres:15"
    volumes:
    - "./data/postgres:/var/lib/postgresql/data"
    - "./postgres:/docker-entrypoint-initdb.d"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # provides:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SANDBOX_DB_PASSWORD: "${SANDBOX_DB_PASSWORD}"
      NEXUS_DB_PASSWORD: "${NEXUS_DB_PASSWORD}"
      EXCHANGE_DB_PASSWORD: "${EXCHANGE_DB_PASSWORD}"
  libeufin_sandbox:
    image: "libeufin-sandbox"
    environment:
      # consumes:
      LIBEUFIN_SANDBOX_DB_CONNECTION: "jdbc:postgresql://postgres/sandbox?user=sandbox&password=${SANDBOX_DB_PASSWORD}"
      EXCHANGE_URL: "https://taler.windfis.ch/"
      PAYTO_URL: "payto://iban/${MYIBAN}?receiver-name=MyExchange"
      # provides:
      LIBEUFIN_SANDBOX_ADMIN_PASSWORD: "${SANDBOX_ADMIN_PASSWORD}"
      ACCOUNT_NAME: jrluser
      ACCOUNT_IBAN: "${MYIBAN}"
      EBICS_PARTNER: partner01
      EBICS_USER: user02
      EBICS_HOST: testhost
    ports:
      - "5016:5016"
  libeufin_nexus:
    image: "libeufin-nexus"
    environment:
      # consumes:
      LIBEUFIN_NEXUS_DB_CONNECTION: "jdbc:postgresql://postgres/nexus?user=nexus&password=${NEXUS_DB_PASSWORD}"
      ACCOUNT_NAME: jrluser
      EBICS_URL: "http://libeufin_sandbox:5016/ebicsweb"
      EBICS_PARTNER: partner01
      EBICS_USER: user02
      EBICS_HOST: testhost
      # provides:
      ADMIN_USER: admin
      ADMIN_PASSWORD: "${NEXUS_ADMIN_PASSWORD}"
      TALER_USER: taler
      TALER_PASSWORD: "${NEXUS_TALER_PASSWORD}"
      CONNECTION_NAME: myconnection
      ACCOUNT_NICKNAME: nickname
      TALER_FACADE_NAME: taler-facade
  exchange:
    image: "taler-exchange-insecure"
    ports:
      - "8081:8081"
    environment:
      # provides:
      BASE_URL: "http://localhost:8081"
      # consumes:
      MYIBAN: "${MYIBAN}"
      MYCURRENCY: "${MYCURRENCY}"
    volumes:
      # consumes NEXUS_DB_PASSWORD, NEXUS_TALER_PASSWORD, MYCURRENCY, MYIBAN via make_env.sh
      - ./exchange-config:/etc/taler/
      - ./data/taler:/var/lib/taler/

# vim: expandtab:sw=2
